// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqhU77vyXKclghzHZRIEgcx_04g8fgNJs',
    appId: '1:764884460203:web:dad58b9582688fd6b40dee',
    messagingSenderId: '764884460203',
    projectId: 'scb-mobile-database',
    authDomain: 'scb-mobile-database.firebaseapp.com',
    databaseURL: 'https://scb-mobile-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scb-mobile-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiy7D9id0bFsxi4gChpNmaMiiu7VD5dTA',
    appId: '1:764884460203:android:f6a9bdfc5a07f8d1b40dee',
    messagingSenderId: '764884460203',
    projectId: 'scb-mobile-database',
    databaseURL: 'https://scb-mobile-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scb-mobile-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRPBRJUEOSHxrHfnwdHtXB8Yr3EUmA4lY',
    appId: '1:764884460203:ios:af696d458c7d3983b40dee',
    messagingSenderId: '764884460203',
    projectId: 'scb-mobile-database',
    databaseURL: 'https://scb-mobile-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scb-mobile-database.appspot.com',
    iosClientId: '764884460203-ftgqutnqkm0afcqmo1cjfdeud8ohsgor.apps.googleusercontent.com',
    iosBundleId: 'com.example.scbMobileBanking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRPBRJUEOSHxrHfnwdHtXB8Yr3EUmA4lY',
    appId: '1:764884460203:ios:c88c2c8a27530909b40dee',
    messagingSenderId: '764884460203',
    projectId: 'scb-mobile-database',
    databaseURL: 'https://scb-mobile-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scb-mobile-database.appspot.com',
    iosClientId: '764884460203-g9heb5rc2av45klnkvep7munotfvrv74.apps.googleusercontent.com',
    iosBundleId: 'com.example.scbMobileBanking.RunnerTests',
  );
}
